package resource

import (
	"context"
	"fmt"
	"os"

	"github.com/spf13/cobra"
	"gitlab.com/jacky850509/secra/internal/config"
	"gitlab.com/jacky850509/secra/internal/repo"
	"gitlab.com/jacky850509/secra/internal/service"
	"gitlab.com/jacky850509/secra/internal/storage"
)

var createCveCmd = &cobra.Command{
	Use:   "create-cve",
	Short: "Create a new CVE record",
	Run: func(cmd *cobra.Command, args []string) {
		cfg := config.Load()
		db := storage.NewDB(cfg.PostgresDSN, false)
		cveRepo := repo.NewCVERepo(db.DB)
		svc := service.NewCveService(cveRepo)

		// id is auto-generated by database; do not read flag
		sourceID, _ := cmd.Flags().GetString("source-id")
		sourceUID, _ := cmd.Flags().GetString("source-uid")
		title, _ := cmd.Flags().GetString("title")
		description, _ := cmd.Flags().GetString("description")

		cve, err := svc.Create(context.Background(), "", sourceID, sourceUID, title, description)
		if err != nil {
			fmt.Fprintf(os.Stderr, "error: %v\n", err)
			os.Exit(1)
		}
		fmt.Printf("Created CVE: ID=%s SourceID=%s SourceUID=%s\n", cve.ID, cve.SourceID, cve.SourceUID)
	},
}

func init() {
	Cmd.AddCommand(createCveCmd)
	createCveCmd.Flags().String("source-id", "", "Resource ID")
	createCveCmd.Flags().String("source-uid", "", "Original CVE identifier")
	createCveCmd.Flags().String("title", "", "CVE title")
	createCveCmd.Flags().String("description", "", "CVE description")
	createCveCmd.MarkFlagRequired("source-id")
	createCveCmd.MarkFlagRequired("source-uid")
	createCveCmd.MarkFlagRequired("source-id")
	createCveCmd.MarkFlagRequired("source-uid")
	createCveCmd.MarkFlagRequired("title")
	createCveCmd.MarkFlagRequired("description")
}
